-- 1.
SELECT * FROM N, O;

-- 2.
SELECT TEILNEHEMER FROM N INNER JOIN O ON N.ORT = O.ORT WHERE N.ORT IS NOT NULL;

-- 3.
SELECT TEILNEHEMER FROM N INNER JOIN O ON N.ORT = O.ORT WHERE N.ORT = '06109';

-- 4.
SELECT TEILNEHEMER FROM N WHERE ORT NOT IN (SELECT ORT FROM O WHERE VORWAHL IS NOT NULL);

-- 5.
SELECT ORT FROM N WHERE ORT NOT IN (
    SELECT ORT FROM O WHERE VORWAHL IS NOT NULL
) 
UNION 
SELECT ORT FROM O WHERE ORT NOT IN (
    SELECT ORT FROM N;
);